<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\Business; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class DevelopmentKeyController extends Controller {
 private function business(Request $r,string $id):Business{return Business::ownedBy($r->attributes->get('user_id'))->findOrFail($id);}
 public function store(Request $r,string $business):JsonResponse{$b=$this->business($r,$business);$d=$r->validate(['name'=>['required','string','max:120'],'key_type'=>['required','string','max:50'],'environment'=>['required','in:development,staging,production'],'description'=>['nullable','string','max:1000'],'secret'=>['required','string','max:10000'],'is_active'=>['sometimes','boolean']]);return DB::transaction(function()use($b,$d,$r){$row=DB::selectOne('select vault.create_secret(?, ?, ?) as id',[$d['secret'],'nexarch_'.$b->id.'_'.str()->uuid(),$d['description']??null]);unset($d['secret']);$x=$b->developmentKeys()->create($d+['vault_secret_id'=>$row->id,'user_id'=>$r->attributes->get('user_id')]);return response()->json($x,201);});}
 public function update(Request $r,string $business,string $key):JsonResponse{$x=$this->business($r,$business)->developmentKeys()->whereKey($key)->firstOrFail();$d=$r->validate(['name'=>['sometimes','string','max:120'],'key_type'=>['sometimes','string','max:50'],'environment'=>['sometimes','in:development,staging,production'],'description'=>['sometimes','nullable','string','max:1000'],'secret'=>['sometimes','string','max:10000'],'is_active'=>['sometimes','boolean']]);return DB::transaction(function()use($x,$d){if(isset($d['secret'])){DB::statement('select vault.update_secret(?, ?, null, null)',[$x->vault_secret_id,$d['secret']]);unset($d['secret']);}$x->update($d);return response()->json($x->fresh());});}
 public function destroy(Request $r,string $business,string $key):JsonResponse{$x=$this->business($r,$business)->developmentKeys()->whereKey($key)->firstOrFail();DB::transaction(function()use($x){DB::delete('delete from vault.secrets where id = ?',[$x->vault_secret_id]);$x->delete();});return response()->json(null,204);}
}
